import { parseArgs } from 'node:util'

import { readEnv } from '../env.js'

import { runConfigCheck } from './config-check.js'

import type { CliEnv } from '../env.js'
import type { ConfigCheckResult, FetchLike } from './config-check.js'

export const INIT_HELP = `Usage: afr init [options]

Get from zero to a recorded run in one command. This is the frictionless
first-run onboarding path: it (a) checks AFR_API_KEY / AFR_BASE_URL and
pings the backend (same checks as 'afr config check'), (b) writes a small,
runnable starter file that imports the SDK and records a tiny demo run
end-to-end against your configured backend, and (c) prints exact next
steps.

Options:
  --out <file>    Path to write the starter file (default: afr-quickstart.mjs)
  --force         Overwrite the starter file if it already exists
  --help          Show this message
`

export interface InitArgs {
  out?: string
  force?: boolean
  help?: boolean
}

/** Parse `afr init` args (argv AFTER `init`). */
export function parseInitArgs(argv: string[]): InitArgs {
  const { values } = parseArgs({
    args: argv,
    allowPositionals: false,
    options: {
      out: { type: 'string' },
      force: { type: 'boolean' },
      help: { type: 'boolean', short: 'h' },
    },
  })
  const result: InitArgs = {}
  if (values['out']) result.out = values['out']
  if (values['force']) result.force = true
  if (values['help']) result.help = true
  return result
}

export const DEFAULT_QUICKSTART_FILE = 'afr-quickstart.mjs'

/** Injectable existence check so tests never touch a real filesystem. */
export type FileExistsLike = (path: string) => Promise<boolean>

/** Injectable file writer, same shape as `afr export`'s (see `commands/export.ts`). */
export type WriteFileLike = (path: string, content: string) => Promise<void>

async function defaultFileExists(path: string): Promise<boolean> {
  const { access } = await import('node:fs/promises')
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function defaultWriteFile(path: string, content: string): Promise<void> {
  const { writeFile } = await import('node:fs/promises')
  await writeFile(path, content, 'utf8')
}

/**
 * The runnable starter file's contents — a plain ESM script (no build step,
 * no TypeScript compile) that records one small demo run end-to-end through
 * `@agent-flight-recorder/sdk`'s `Recorder`, then prints the run's web URL.
 * Reads `AFR_API_KEY`/`AFR_BASE_URL` from the environment, mirroring how the
 * rest of `afr` is configured — this is the one place the *generated*
 * customer script reads `process.env` directly; the SDK itself never does
 * (CLAUDE.md/SDK boundary rules), and this string is just a template, not
 * SDK source.
 */
export function quickstartFileContents(): string {
  return `#!/usr/bin/env node
// Generated by \`afr init\`. Safe to edit or delete once you've wired up your
// own agent — this file exists to prove your AFR_API_KEY / AFR_BASE_URL are
// configured correctly by recording one small demo run end-to-end.
//
// Run: node ${DEFAULT_QUICKSTART_FILE}

import { Recorder, Events } from '@agent-flight-recorder/sdk'

const apiKey = process.env.AFR_API_KEY
const baseUrl = process.env.AFR_BASE_URL

if (!apiKey || !baseUrl) {
  console.error('AFR_API_KEY and AFR_BASE_URL must both be set. Run \`afr config check\` for details.')
  process.exit(1)
}

const recorder = new Recorder({ endpoint: baseUrl, apiKey, agentId: 'afr-quickstart' })

const run = await recorder.startRun({ demo: true }, { source: 'afr-init', name: 'afr-quickstart-run' })

recorder.recordEvent(
  'llm.request',
  Events.llmRequest('demo-model', [{ role: 'user', content: 'What is 2 + 2?' }]).payload
)
recorder.recordEvent(
  'llm.response',
  Events.llmResponse('demo-model', '4', { prompt_tokens: 6, completion_tokens: 1, total_tokens: 7 }, 'stop').payload
)
recorder.recordEvent('tool.call', Events.toolCall('calculator', { expression: '2 + 2' }, 'call_quickstart_1').payload)
recorder.recordEvent('tool.result', Events.toolResult('call_quickstart_1', { result: 4 }, 3).payload)

const result = await recorder.endRun({ answer: 4 })

if (!result.success) {
  console.error('Demo run did not fully deliver:', result.errors)
  process.exit(1)
}

console.log(\`Recorded run \${run.runId}\`)
console.log(\`View it at: \${baseUrl.replace(/\\/$/, '')}/runs/\${run.runId}\`)
`
}

export type InitResult =
  | {
      ok: true
      exitCode: number
      wrote: boolean
      path: string
      skippedReason?: 'exists'
      configCheck: ConfigCheckResult
    }
  | { ok: false; exitCode: number; message: string; configCheck: ConfigCheckResult }

/**
 * `afr init` — frictionless first-run onboarding: report config status,
 * write a runnable starter file (never overwriting an existing one unless
 * `--force`), and print next steps to get from zero to a recorded run.
 *
 * Writing the starter file never depends on `AFR_API_KEY`/`AFR_BASE_URL`
 * already being valid — a brand new user with nothing configured yet still
 * gets the file, plus the config-check output telling them what to set
 * before running it.
 */
export async function runInit(
  args: InitArgs = {},
  env: CliEnv = readEnv(),
  fetchImpl?: FetchLike,
  fileExistsImpl: FileExistsLike = defaultFileExists,
  writeFileImpl: WriteFileLike = defaultWriteFile
): Promise<InitResult> {
  const configCheck = await runConfigCheck(env, fetchImpl)
  const path = args.out ?? DEFAULT_QUICKSTART_FILE

  if (!args.force) {
    let exists: boolean
    try {
      exists = await fileExistsImpl(path)
    } catch (err) {
      return {
        ok: false,
        exitCode: 4,
        message: `Failed to check for an existing ${path}: ${err instanceof Error ? err.message : String(err)}`,
        configCheck,
      }
    }
    if (exists) {
      return { ok: true, exitCode: configCheck.ok ? 0 : 1, wrote: false, path, skippedReason: 'exists', configCheck }
    }
  }

  try {
    await writeFileImpl(path, quickstartFileContents())
  } catch (err) {
    return {
      ok: false,
      exitCode: 4,
      message: `Failed to write ${path}: ${err instanceof Error ? err.message : String(err)}`,
      configCheck,
    }
  }

  return { ok: true, exitCode: configCheck.ok ? 0 : 1, wrote: true, path, configCheck }
}

export function printInit(result: InitResult, log: (line: string) => void = console.log): void {
  for (const c of result.configCheck.checks) {
    log(`[${c.status === 'ok' ? 'ok' : 'fail'}] ${c.name}: ${c.message}`)
  }
  log('')

  if (!result.ok) {
    log(`Error: ${result.message}`)
    return
  }

  if (result.skippedReason === 'exists') {
    log(`Skipped writing ${result.path} — it already exists. Pass --force to overwrite it.`)
  } else {
    log(`Wrote starter file: ${result.path}`)
  }
  log('')

  log('Next steps:')
  let step = 1
  if (!result.configCheck.ok) {
    log(`  ${step++}. Set AFR_API_KEY / AFR_BASE_URL (see the checks above), then re-run \`afr config check\` to confirm.`)
  }
  log(`  ${step++}. Run: node ${result.path}`)
  log(`  ${step++}. Run: afr runs list`)
}
