import { expect, test } from '@playwright/test'

import {
  ACK_NO_AUTH_COVERAGE_ENV,
  AUTHENTICATED_JOURNEYS,
  readAuthTierConfig,
  renderZeroCoverageReport,
} from './support/auth-tier'

/**
 * The coverage guard.
 *
 * This suite used to contain a `test.skip(true, …)` for the authenticated
 * tier. A skip is a reassuring signal generated by an absence of information:
 * the run went green, the summary said "1 skipped", and the fact that NO
 * signed-in user journey had ever been exercised was a footnote nobody read.
 *
 * This file replaces that with a failure. When the authenticated tier is not
 * configured, the run reports — as a test result, in the same place every other
 * result appears — that authenticated coverage is exactly zero, which journeys
 * were not run, and what to provision.
 *
 * It deliberately does NOT open a browser or touch the app. It is an assertion
 * about the shape of the test run itself.
 *
 * NOTE ON THE ESCAPE HATCH: setting AFR_E2E_ACK_NO_AUTH_COVERAGE=1 downgrades
 * the failure to an annotation. The report is still printed. That variable
 * records an accepted gap; it does not close one. It must never be added to CI
 * as a way of restoring green.
 */

test.describe('authenticated tier coverage', () => {
  test('the authenticated tier is configured and its journeys will run', () => {
    const config = readAuthTierConfig()

    if (config.configured) {
      // Nothing to report: the authenticated project exists in this run and
      // its journeys execute alongside this test.
      expect(AUTHENTICATED_JOURNEYS.length).toBeGreaterThan(0)
      return
    }

    const report = renderZeroCoverageReport(config)

    // Always emit the report, whether or not the failure is acknowledged, so
    // the information exists in the run output either way.
    console.error(`\n${report}\n`)
    test.info().annotations.push({
      type: 'authenticated-coverage',
      description: `0 of ${String(AUTHENTICATED_JOURNEYS.length)} authenticated journeys ran. Missing: ${config.missing.join(', ')}`,
    })

    if (process.env[ACK_NO_AUTH_COVERAGE_ENV] === '1') {
      test.info().annotations.push({
        type: 'acknowledged-gap',
        description: `${ACK_NO_AUTH_COVERAGE_ENV}=1 — zero authenticated coverage is being consciously accepted for this run.`,
      })
      return
    }

    // Not a skip. A failure, with the whole report as the message.
    expect(config.configured, report).toBe(true)
  })
})
