import Link from 'next/link'

import type { RunExplanation } from '@/lib/services/explanations'

import { ExplanationRegenerateButton } from '@/components/runs/ExplanationRegenerateButton'
import { isStillAnalyzing } from '@/lib/services/explanations'
import { formatRelativeTime } from '@/lib/utils'

interface ExplanationPanelProps {
  runId: string
  /** null = no explanation yet (still generating, or never triggered). Distinct from loadFailed. */
  explanation: RunExplanation | null
  /** True when the explanation fetch itself threw — additive/non-fatal, rest of the page still renders. */
  loadFailed: boolean
  isAdmin: boolean
  /**
   * The run's terminal timestamp (`run.endedAt`), if any. Used only to soften
   * the "coarse null" gap (see `lib/services/explanations.ts`): a `null`
   * explanation covers both "still generating" and "never triggered / never
   * will be", and this component can't tell those apart from the data it
   * gets. Once a run has been over for a while with still no explanation,
   * showing an indefinite pulsing "Analyzing…" is dishonest — it looks like
   * live work is happening when it almost certainly is not. Past the
   * threshold this renders a neutral "not available" message instead.
   */
  runEndedAt?: number
}

function formatFailureClass(cls: string): string {
  return cls.replace(/_/g, ' ')
}

/**
 * The flagship "Why did this fail?" panel. Sits above the timeline on a
 * failed/timed_out run's detail page — the first thing an engineer sees.
 * Server component: the only interactive piece (regenerate) is isolated into
 * ExplanationRegenerateButton so this stays server-rendered.
 *
 * Cited event numbers link to `?tab=timeline&event=<seq>` — Timeline reads
 * that same `event` query param (see RunDetailPage) to scroll to and
 * highlight the cited event, and marks every cited event with a left-accent
 * tick so the causal chain stays visible in context, not just from here.
 */
export function ExplanationPanel({ runId, explanation, loadFailed, isAdmin, runEndedAt }: ExplanationPanelProps) {
  const stillAnalyzing = isStillAnalyzing(runEndedAt)

  return (
    <section
      aria-label="Why this run failed"
      className="mx-6 mt-4 rounded-[4px] border border-graphite-light bg-graphite-deep px-5 py-4"
    >
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-mono uppercase tracking-wider text-pewter">Why did this fail?</h2>
        {isAdmin && <ExplanationRegenerateButton runId={runId} />}
      </div>

      {loadFailed ? (
        <p className="text-sm text-pewter">
          Couldn&apos;t load the failure analysis for this run — refresh to retry.
        </p>
      ) : !explanation ? (
        stillAnalyzing ? (
          <div className="flex items-center gap-2">
            <span
              className="w-1.5 h-1.5 rounded-full bg-neon-glow animate-neon-pulse shrink-0 forced-colors:bg-[Highlight]"
              aria-hidden="true"
            />
            <p className="text-sm text-pewter">Analyzing this run&apos;s failure…</p>
          </div>
        ) : (
          <p className="text-sm text-pewter">
            No failure analysis is available for this run.
            {isAdmin && ' Use Regenerate above to run one now.'}
          </p>
        )
      ) : (
        <div className="flex flex-col gap-3">
          {/* Failure class + honest provenance — never implies AI on the heuristic path */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="inline-flex items-center px-2 py-0.5 rounded-[4px] text-xs font-mono font-medium border bg-destructive-900/40 text-destructive-400 border-destructive-700/60">
              {formatFailureClass(explanation.failureClass)}
            </span>
            <span
              className="text-xs font-mono text-pewter"
              title={
                explanation.kind === 'llm'
                  ? `Generated by an AI model${explanation.model ? ` (${explanation.model})` : ''}`
                  : 'Generated by deterministic rules over the event log — no model involved'
              }
            >
              {explanation.kind === 'llm'
                ? `AI-generated${explanation.model ? ` · ${explanation.model}` : ''}`
                : 'Heuristic · deterministic'}
            </span>
          </div>

          {/* Hero line — prose for a human, not mono */}
          <p className="text-base leading-relaxed text-whiteout">{explanation.summary}</p>

          {explanation.rootCause && (
            <div>
              <p className="text-xs font-mono uppercase tracking-wider text-pewter mb-1">Root cause</p>
              <p className="text-sm leading-relaxed text-neutral-300">{explanation.rootCause}</p>
            </div>
          )}

          {/* Suggested fix — visually distinct, actionable tone */}
          {explanation.suggestedFix && (
            <div className="rounded-[4px] border border-neon-muted bg-primary-900/20 px-3 py-2.5">
              <p className="text-xs font-mono uppercase tracking-wider text-neon-glow mb-1">Suggested fix</p>
              <p className="text-sm leading-relaxed text-neutral-200">{explanation.suggestedFix}</p>
            </div>
          )}

          {/* Cited events — the grounding made visible. Clicking one jumps to
              the Timeline tab, scrolled to and highlighting that event. */}
          {explanation.citedSequenceNumbers.length > 0 && (
            <div className="flex flex-wrap items-center gap-1.5 pt-2 border-t border-graphite">
              <span className="text-xs text-pewter mr-1">Grounded in:</span>
              {explanation.citedSequenceNumbers.map((seq) => (
                <Link
                  key={seq}
                  href={`/runs/${runId}?tab=timeline&event=${seq}`}
                  aria-label={`Jump to event ${seq}`}
                  className="inline-flex items-center px-1.5 py-0.5 rounded-[4px] text-xs font-mono text-neon-glow bg-primary-900/30 border border-primary-800 hover:bg-primary-900/60 hover:border-primary-700 transition-colors duration-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neon-glow"
                >
                  #{seq}
                </Link>
              ))}
            </div>
          )}

          <p className="text-xs font-mono text-pewter">
            Generated {formatRelativeTime(explanation.generatedAt)}
          </p>
        </div>
      )}
    </section>
  )
}
